# Generated by Django 3.1.3 on 2020-12-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListWithTasks',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('context', models.CharField(max_length=100)),
                ('condition', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'list_with_tasks',
                'managed': False,
            },
        ),
    ]
